### ISSUE TITLE
KeyError: 'y'   when I use gps.geotiff.get(...)

### ISSUE THREAD

**Issue by hll1213181368** [locationtech-labs/geopyspark#579] opened 2017-12-10 15:31 UTC
![2017-12-10 23-22-50](https://user-images.githubusercontent.com/17724484/33806351-e3df8f70-de01-11e7-8842-d473744aa884.png)

I install the Anaconda3,use python3.6.3.Hadoop 2.6.5.Spark-1.6.0-bin-hadoop2.6.

Anyone know this problem! I am in hurry to solve it~

Thanks!

**Comment by jpolchlo** [comment] 2017-12-11 13:36
Not sure if this is the cause of your problem, but I most of the GeoPySpark devs are running Spark version > 2.0 and hadoop 2.7.  If that fixes your problem, let us know, since we should update the docs to reflect that requirement.

**Comment by jpolchlo** [comment] 2017-12-11 13:39
This is a duplicate of #578.  Refer comments to that issue.

**Closed by jpolchlo** 2017-12-11 13:39 UTC
